### ISSUE TITLE
LuaSkin: hs.canvas:Fira Mono is not a recognized font name

### ISSUE THREAD

**Issue by fbion** [boomker/spacehammer#2]
2023-10-01 11:03:36: 11:03:36 ERROR:   LuaSkin: hs.canvas:Fira Mono is not a recognized font name
2023-10-01 11:03:36: *** ERROR: ...merspoon.app/Contents/Resources/extensions/hs/canvas.lua:526: bad argument #2 to 'canvasDefaultFor' (invalid argument type for textFont specified)
stack traceback:
	[C]: in method 'canvasDefaultFor'
	...merspoon.app/Contents/Resources/extensions/hs/canvas.lua:526: in metamethod 'newindex'
	...ntents/Resources/extensions/hs/drawing_canvasWrapper.lua:161: in function 'hs.drawing_canvasWrapper.getTextDrawingSize'
	...mmerspoon.app/Contents/Resources/extensions/hs/alert.lua:140: in function <...mmerspoon.app/Contents/Resources/extensions/hs/alert.lua:78>
	(...tail calls...)
	/Users/host/.hammerspoon/configs/shortcuts.lua:109: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/host/.hammerspoon/modules/emoji.lua:5: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/host/.hammerspoon/configs/menu.lua:42: in local 'renderMenubar'
	/Users/host/.hammerspoon/configs/menu.lua:66: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/host/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by boomker** [comment]
You can try a different font setting，Like this：
```lua
hs.alert.defaultStyle.textFont = "FiraCode Nerd Font"
```
[defaultStyle.textFont](https://github.com/boomker/spacehammer/blob/0a1419b0b5f54ee77c0a53684d64ebf11a969e7e/configs/baseConfig.lua#L7C54-L7C54)
