### ISSUE TITLE
emoji 表情发送功能异常

### ISSUE THREAD

**Issue by YoungXAI** [boomker/spacehammer#3]
1. install.sh的逻辑错了，目录有问题

2.整个项目配置也有问题，024-12-12 15:06:53: -- Loading extension: chooser
2024-12-12 15:06:53: *** ERROR: /Users/ouyangzhaoxin/.hammerspoon/modules/emoji.lua:32: ERROR: incorrect type 'no value' for argument 1 (expected function)
stack traceback:
	[C]: in function 'hs.libchooser.new'
	/Users/ouyangzhaoxin/.hammerspoon/modules/emoji.lua:32: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/ouyangzhaoxin/.hammerspoon/configs/menu.lua:42: in local 'renderMenubar'
	/Users/ouyangzhaoxin/.hammerspoon/configs/menu.lua:66: in main chunk
	[C]: in function 'rawrequire'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:662: in function 'require'
	/Users/ouyangzhaoxin/.hammerspoon/init.lua:1: in main chunk
	[C]: in function 'xpcall'
	...poon.app/Contents/Resources/extensions/hs/_coresetup.lua:723: in function 'hs._coresetup.setup'
	(...tail calls...)

**Comment by boomker** [comment]
已经修复了，拉取项目最新代码试试看
emoji 这个功能之前是依赖一个在线表情包网站的服务，因为网站停服了，所以用不了了，现在换了一个网站，可以正常用了
不过，首次用，可能得有点卡顿感(要下载表情包的图片到本地)
